"""No-op Teacher: deterministic stub used until a real LLM provider is wired."""

from __future__ import annotations

from .base import TeacherPlan, TeacherProvider


class NoopTeacher(TeacherProvider):
    name = "noop"

    def plan(self, task: str, context: str) -> TeacherPlan:
        return TeacherPlan(
            task=task,
            summary=(
                "Placeholder plan generated by the noop Teacher. "
                "Wire a real provider in .minion/config.yaml to replace this."
            ),
            steps=[
                "Review the candidate files listed in this brief.",
                "Identify the smallest change that satisfies the task.",
                "Implement and run the project's test suite.",
            ],
            acceptance=[
                "Behavior described by the task is implemented.",
                "Existing tests still pass.",
                "New behavior has at least one test.",
            ],
            risks=[
                "Scope creep beyond the task description.",
                "Hidden coupling not visible from filenames alone.",
            ],
        )
